obj-$(CONFIG_INTEL_NORTHPEAK) += npk_pci.o
obj-$(CONFIG_INTEL_NORTHPEAK_UTIL) += npk_util.o
obj-$(CONFIG_INTEL_NORTHPEAK_TRACE) += npk_trace.o
obj-$(CONFIG_INTEL_NORTHPEAK_EARLY_PRINTK) += npk_early_printk.o